//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : ActionBubble.java
//  @ Date : 2022. 05. 07.
//  @ Author : 
//
//




public class ActionBubble extends Observer {
	public Window Unnamed1;
	public void update() {
	}
}
