//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Game.java
//  @ Date : 2022. 05. 07.
//  @ Author : 
//
//




public class Game extends Subject {
	public Subject Unnamed2;
	private Subject subjects;
}
