//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Main.java
//  @ Date : 2022. 05. 07.
//  @ Author : 
//
//




public class Main {
	public static void main(String[] args) {
	}
}
