package model.strategy;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : strategy.DefDrop.java
//  @ Date : 2022. 03. 23.
//  @ Author : 
//
//



import model.Virologist;
import model.equipments.Equipment;
import test.Tester;

/**
 * Alapértelmezett eldobási stratégia, ami által a virológus eldob egy felszerelést.
 */
public class DefDrop implements IDropStr
{
	/**
	 * A stratégia alkalmazásakor hívott metódus.
	 * Eldobja a virológus a megadott felszerlést, majd csökkenti az akciói számát eggyel.
	 * @param v A virológus, aki el próbál dobni egy felszerelést.
	 * @param e A felszerelés, amit el próbál dobni.
	 */
	public void Drop(Virologist v, Equipment e)
	{
		Tester.methodStart(new Object(){}.getClass().getEnclosingMethod());

		e.Disable(v);
		v.getField().Drop(e);
		v.Reset();
		v.DecreaseActions();

		Tester.methodEnd(new Object(){}.getClass().getEnclosingMethod());
	}
}
