package model.strategy;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : strategy.IDropStr.java
//  @ Date : 2022. 03. 23.
//  @ Author : 
//
//



import model.Virologist;
import model.equipments.Equipment;

/**
 * A virológus azon stratégiáját reprezentálja, amikor el próbál dobni egy felszerelést.
 */
public interface IDropStr {

	/**
	 * A stratégia alkalmazásakor hívott metódus.
	 * @param v A virológus, aki el próbál dobni egy felszerelést.
	 * @param e A felszerelés, amit el próbál dobni.
	 */
	void Drop(Virologist v, Equipment e);

}
