package model.strategy;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : strategy.IMoveStr.java
//  @ Date : 2022. 03. 23.
//  @ Author : 
//
//



import model.Virologist;
import model.map.Field;

/**
 * A virológus azon stratégiáját reprezentálja, amikor át próbál lépni egy másik mezőre.
 */
public interface IMoveStr
{
	/**
	 * A stratégia alkalmazásakor hívott metódus.
	 * @param v A virológus, aki lépni próbál.
	 * @param f A mező, amire lépni próbál.
	 */
	void Move(Virologist v, Field f);
}
