//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Loader.java
//  @ Date : 2022. 05. 07.
//  @ Author : 
//
//




public class Loader {
	public Game loadGame(String path) {
	}
}
