//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Subject.java
//  @ Date : 2022. 05. 07.
//  @ Author : 
//
//




public class Subject {
	private Observer observers;
	public Game Unnamed2;
	public void attach(Observer o) {
	}
	
	public void detach(Observer o) {
	}
	
	public void notifyAllObservers() {
	}
}
