package model.agents;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : agents.Agent.java
//  @ Date : 2022. 03. 23.
//  @ Author : 
//
//


import model.Virologist;


public abstract class Agent
{
	private int timeToLive;

	public void Update(Virologist v)
	{
	}
	
	public boolean Validate()
	{
	}
	
	public void Apply(Virologist v)
	{
	}
	
	public void ApplyStrategy(Virologist v)
	{
	}
}
