package model.agents;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : agents.Chorea.java
//  @ Date : 2022. 03. 23.
//  @ Author : 
//
//


import model.Virologist;

public class Chorea extends Agent
{
	public void Apply(Virologist v)
	{
	}
}
