//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : DrawableGlove.java
//  @ Date : 2022. 05. 07.
//  @ Author : 
//
//




public class DrawableGlove extends Glove, Drawable implements Drawable {
	public String getTexture() {
	}
}
