//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : DrawableAxe.java
//  @ Date : 2022. 05. 07.
//  @ Author : 
//
//




public class DrawableAxe extends Axe, Drawable implements Drawable {
	public String getTexture() {
	}
}
