//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : DrawableField.java
//  @ Date : 2022. 05. 07.
//  @ Author : 
//
//




public class DrawableField extends Laboratory, Field ., Shelter, Warehouse, InfectedLaboratory, Drawable, Field . implements Drawable {
	public String getTexture() {
	}
}
