//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Observer.java
//  @ Date : 2022. 05. 07.
//  @ Author : 
//
//




public abstract class Observer implements Window {
	public Subject Unnamed1;
	private Window Unnamed2;
	public abstract void update();
}
