//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : DrawableShelter.java
//  @ Date : 2022. 05. 07.
//  @ Author : 
//
//




public class DrawableShelter extends Shelter, Drawable implements Drawable {
	public String getTexture() {
	}
}
