//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Controller.java
//  @ Date : 2022. 05. 07.
//  @ Author : 
//
//




public class Controller extends Subject, Observer, Subject {
	public Object actionMessage;
	private Game game;
	private Window window;
	public void Controller(Game game) {
	}
	
	public void attack(Virologist v) {
	}
	
	public void move(Field f) {
	}
	
	public void drop() {
	}
	
	public void lootAminoFrom(Virologist v) {
	}
	
	public void lootNucleoFrom(Virologist v) {
	}
	
	public void lootEquipmentFrom(Virologist v) {
	}
	
	public void collect() {
	}
	
	public void learn() {
	}
	
	public void equip() {
	}
	
	public void inject(Virologist v, GeneticCode code) {
	}
	
	public void endTurn() {
	}
	
	public String getActionMessage() {
	}
	
	public void update() {
	}
}
