package model.strategy;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : strategy.DefCollect.java
//  @ Date : 2022. 03. 23.
//  @ Author : 
//
//


import model.Virologist;
import model.map.Field;
import test.Tester;

public class DefCollect implements ICollectStr
{
	@Override
	public void Collect(Virologist v, Field f) {
		Tester.methodStart(new Object(){}.getClass().getEnclosingMethod());

		f.CollectMaterial(v);

		Tester.methodEnd(new Object(){}.getClass().getEnclosingMethod());
	}

}
