package model.strategy;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : strategy.DefCollect.java
//  @ Date : 2022. 03. 23.
//  @ Author : 
//
//


import model.Virologist;
import test.Tester;

/**
 * Alapértelmezett aminosav vagy nukleotid gyűjtési stratégia, ami által a virológus aminosavat vagy nukleotidot
 * gyűjt össze a mezőről, ha van ott olyan.
 */
public class DefCollect implements ICollectStr
{
	/**
	 * Az aminosav gyűjtés stratégia alkalmazásakor hívott metódus.
	 * Adott mennyiségű aminosavat ad a virológusnak, ha van a mezőn.
	 * @param v A virológus, aki aminosavat próbál összegyűjteni.
	 */
	@Override
	public void CollectAminoacid(Virologist v) {
		Tester.methodStart(new Object(){}.getClass().getEnclosingMethod());

		v.getField().CollectNucleotide(v);

		Tester.methodEnd(new Object(){}.getClass().getEnclosingMethod());
	}

	/**
	 * A nukleotid gyűjtés stratégia alkalmazásakor hívott metódus.
	 * Adott mennyiségű nukleotidot ad a virológusnak, ha van a mezőn.
	 * @param v A virológus, aki nukleotidot próbál összegyűjteni.
	 */
	@Override
	public void CollectNucleotide(Virologist v) {
		Tester.methodStart(new Object(){}.getClass().getEnclosingMethod());

		v.getField().CollectAminoacid(v);

		Tester.methodEnd(new Object(){}.getClass().getEnclosingMethod());
	}
}
