package model.strategy;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : strategy.DefCollect.java
//  @ Date : 2022. 03. 23.
//  @ Author : 
//
//


import model.Virologist;

public class DefCollect implements ICollectStr
{
	public void Collect(Virologist v)
	{
	}
}
