package model.strategy;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : strategy.DefDrop.java
//  @ Date : 2022. 03. 23.
//  @ Author : 
//
//



import model.Virologist;
import model.equipments.Equipment;
import test.Tester;

public class DefDrop implements IDropStr
{
	/**
	 * TODO
	 */
	public DefDrop(){
		Tester.ctrMethodStart(new Object(){}.getClass().getEnclosingConstructor());
	}

	public void Drop(Virologist v, Equipment e)
	{
		Tester.methodStart(new Object(){}.getClass().getEnclosingMethod());

		e.Disable(v);
		//v.getField().Drop(e);
		v.Reset();
		v.DecreaseActions();

		Tester.methodEnd(new Object(){}.getClass().getEnclosingMethod());
	}
}
