package model.strategy;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : strategy.DefDrop.java
//  @ Date : 2022. 03. 23.
//  @ Author : 
//
//



import model.Virologist;
import model.equipments.Equipment;

public class DefDrop implements IDropStr
{
	public void Drop(Virologist v, Equipment e)
	{
	}
}
