package model.strategy;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : strategy.DefEquip.java
//  @ Date : 2022. 03. 23.
//  @ Author : 
//
//



import model.Virologist;
import model.map.Field;


public class DefEquip implements IEquipStr
{
	public void Equip(Virologist v, Field f)
	{
	}
}
