package model.strategy;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : strategy.DefLoot.java
//  @ Date : 2022. 03. 23.
//  @ Author : 
//
//


import model.Virologist;

public class DefLoot implements ILootStr
{
	public void LootAmino(Virologist v, Virologist target)
	{
	}
	
	public void LootNucleotide(Virologist v, Virologist target)
	{
	}
	
	public void LootEquipment(Virologist v, Virologist target)
	{
	}
}
