package model.strategy;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : strategy.DefMove.java
//  @ Date : 2022. 03. 23.
//  @ Author : 
//
//


import model.Virologist;
import model.map.Field;
import test.Tester;

/**
 * Alapértelmezett lépési stratégia, ami átlépteti a virológust egy másik mezőre.
 */
public class DefMove implements IMoveStr
{
	/**
	 * A stratégia alkalmazásakor hívott metódus.
	 * Átlépteti a virológust a megadott mezőre, és csökkenti eggyel az akcióinak számát.
	 * @param v A virológus, aki lépni próbál.
	 * @param f A mező, amire lépni próbál.
	 */
	public void Move(Virologist v, Field f)
	{
		Tester.methodStart(new Object(){}.getClass().getEnclosingMethod());

		v.getField().RemoveVirologist(v);
		f.AddVirologist(v);
		v.DecreaseActions();

		Tester.methodEnd(new Object(){}.getClass().getEnclosingMethod());
	}
}
