package model.strategy;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : strategy.ICollectStr.java
//  @ Date : 2022. 03. 23.
//  @ Author : 
//
//


import model.Virologist;

/**
 * A virológus azon stratégiáját reprezentálja, amikor aminosavat vagy nukleotidot próbál összegyűjteni.
 */
public interface ICollectStr {

	/**
	 * Az aminosav gyűjtés stratégia alkalmazásakor hívott metódus.
	 * @param v A virológus, aki aminosavat próbál összegyűjteni.
	 */
	void CollectAminoacid(Virologist v);

	/**
	 * A nukleotid gyűjtés stratégia alkalmazásakor hívott metódus.
	 * @param v A virológus, aki nukleotidot próbál összegyűjteni.
	 */
	void CollectNucleotide(Virologist v);

}
