package model.strategy;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : strategy.IDropStr.java
//  @ Date : 2022. 03. 23.
//  @ Author : 
//
//



import model.Virologist;
import model.equipments.Equipment;

public interface IDropStr
{
	void Drop(Virologist v, Equipment e);
}
