package model.strategy;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : strategy.IInjectStr.java
//  @ Date : 2022. 03. 23.
//  @ Author : 
//
//


import model.Virologist;

public interface IInjectStr
{
	void Inject(Virologist v, Virologist target);

}
