package model.strategy;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : strategy.IInjectedStr.java
//  @ Date : 2022. 03. 23.
//  @ Author : 
//
//


import model.Virologist;
import model.agents.Agent;

/**
 * A virológus azon stratégiáját reprezentálja, mikor felkennek rá valamilyen ágenst.
 */
public interface IInjectedStr
{
	/**
	 * A stratégia alakalmazásakor hívott metódus.
	 * @param v A virológus, akire felkenték az ágenst.
	 * @param a A felkent ágens.
	 */
	void Injected(Virologist v, Agent a);
}
