package model.strategy;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : strategy.ILearnStr.java
//  @ Date : 2022. 03. 23.
//  @ Author : 
//
//


import model.Virologist;

public interface ILearnStr
{
	void Learn(Virologist v);

}
