package model.strategy;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : strategy.ILearnStr.java
//  @ Date : 2022. 03. 23.
//  @ Author : 
//
//


import model.Virologist;

/**
 * A virológus azon stratégiáját reprezentálja, amikor meg próbál tanulni egy genetikai kódot.
 */
public interface ILearnStr
{
	/**
	 * A stratégia alkalmazásakor hívott metódus.
	 * @param v A virológus, aki tanulni próbál.
	 */
	void Learn(Virologist v);
}
