package model.strategy;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : strategy.ILootedStr.java
//  @ Date : 2022. 03. 23.
//  @ Author : 
//
//


import model.Virologist;
import model.equipments.Equipment;

public interface ILootedStr
{
	void LootedForEquipment(Virologist v, Virologist from, Equipment e);
	
	void LootedForAminoAcid(Virologist v, Virologist from);
	
	void LootedForNukleotide(Virologist v, Virologist from);
}
