package model.strategy;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : strategy.ILootStr.java
//  @ Date : 2022. 03. 23.
//  @ Author : 
//
//


import model.Virologist;

public interface ILootStr
{
	void LootAmino(Virologist v, Virologist target);
	
	void LootNucleotide(Virologist v, Virologist target);
	
	void LootEquipment(Virologist v, Virologist target);
}
