package model.strategy;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : strategy.Looted.java
//  @ Date : 2022. 03. 23.
//  @ Author : 
//
//


import model.Virologist;
import model.equipments.Equipment;

public class Looted implements ILootedStr
{
	public void LootedForEquipment(Virologist v, Virologist from, Equipment e)
	{
	}
	
	public void LootedForAminoAcid(Virologist v, Virologist from)
	{
	}
	
	public void LootedForNukleotide(Virologist v, Virologist from)
	{
	}
}
