package model.strategy;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : strategy.NoCollect.java
//  @ Date : 2022. 03. 23.
//  @ Author : 
//
//


import model.Virologist;
import test.Tester;

/**
 * Aminosav vagy nukleotid gyűjtési stratégia, amely megakadályozza, hogy egy virológus
 * aminosavat vagy nukleotidot gyűjtsön össze egy mezőről.
 */
public class NoCollect implements ICollectStr
{
	/**
	 * Az aminosav gyűjtés stratégia alkalmazásakor hívott metódus.
	 * Nem végez semmilyen műveletet.
	 * @param v A virológus, aki aminosavat próbál összegyűjteni.
	 */
	@Override
	public void CollectAminoacid(Virologist v) {
		Tester.methodStart(new Object(){}.getClass().getEnclosingMethod());

		Tester.methodEnd(new Object(){}.getClass().getEnclosingMethod());
	}

	/**
	 * Az aminosav gyűjtés stratégia alkalmazásakor hívott metódus.
	 * Nem végez semmilyen műveletet.
	 * @param v A virológus, aki nukleotidot próbál összegyűjteni.
	 */
	@Override
	public void CollectNucleotide(Virologist v) {
		Tester.methodStart(new Object(){}.getClass().getEnclosingMethod());

		Tester.methodEnd(new Object(){}.getClass().getEnclosingMethod());
	}
}
