package model.strategy;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : strategy.NoInject.java
//  @ Date : 2022. 03. 23.
//  @ Author : 
//
//


import model.Virologist;

public class NoInject implements IInjectStr
{
	public void Inject(Virologist v, Virologist target)
	{
	}
}
