package model.strategy;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : strategy.NoInjected.java
//  @ Date : 2022. 03. 23.
//  @ Author : 
//
//



import model.Virologist;
import model.agents.Agent;

public class NoInjected implements IInjectedStr
{
	public void Injected(Virologist v, Agent a)
	{
	}
}
