package model.strategy;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : strategy.NoMove.java
//  @ Date : 2022. 03. 23.
//  @ Author : 
//
//



import model.Virologist;
import model.map.Field;
import test.Tester;

/**
 * Lépési stratégia, amely megakadályozza, hogy egy virológus átlépjen egy másik mezőre.
 */
public class NoMove implements IMoveStr
{
	/**
	 * A stratégia alkalmazásakor hívott metódus.
	 * Nem végez semmilyen műveletet.
	 * @param v A virológus, aki lépni próbál.
	 * @param f A mező, amire lépni próbál.
	 */
	public void Move(Virologist v, Field f)
	{
		Tester.methodStart(new Object(){}.getClass().getEnclosingMethod());

		Tester.methodEnd(new Object(){}.getClass().getEnclosingMethod());
	}
}
