package model.codes;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : codes.ChoreaCode.java
//  @ Date : 2022. 03. 23.
//  @ Author : 
//
//


import model.Virologist;
import model.agents.Agent;

public class ChoreaCode extends GeneticCode
{
	public Agent Create(Virologist v)
	{
	}

}
