package model.codes;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : codes.GeneticCode.java
//  @ Date : 2022. 03. 23.
//  @ Author : 
//
//


import model.Virologist;
import model.agents.Agent;

public abstract class GeneticCode
{
	private int aminoAcidPrice;
	private int nucleotidePrice;
	private int turnsLeft;

	public abstract Agent Create(Virologist v);
}
