package model.equipments;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : equipments.Bag.java
//  @ Date : 2022. 03. 23.
//  @ Author : 
//
//


import model.Virologist;

public class Bag extends Equipment
{
	private int delta;
	public void Apply(Virologist v)
	{
	}
}
