package model.equipments;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : equipments.Equipment.java
//  @ Date : 2022. 03. 23.
//  @ Author : 
//
//


import model.Virologist;

public abstract class Equipment
{
	public void Disable(Virologist v)
	{
	}
	
	public void Apply(Virologist v)
	{
	}
	
	public void ApplyStrategy(Virologist v)
	{
	}
}
