package model.map;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : map.Field.java
//  @ Date : 2022. 03. 23.
//  @ Author : 
//
//



import model.Virologist;
import model.equipments.Equipment;

public class Field
{

	private Field[] neighbours;
	private Virologist[] virologists;
	private Equipment[] equipments;
	public Field[] GetNeighbours()
	{
	}
	
	public void AddNeighbour(Field f)
	{
	}
	
	public void AddVirologist(Virologist v)
	{
	}
	
	public void RemoveVirologist(Virologist v)
	{
	}
	
	public Virologist GetVirologist(int virologist)
	{
	}
	
	public void Drop(Equipment e)
	{
	}
	
	public void LearnGeneticCode(Virologist v)
	{
	}
	
	public void CollectMaterial(Virologist v)
	{
	}
	
	public void PickUpEquipment(Virologist v)
	{
	}
}
