package model.map;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : map.Laboratory.java
//  @ Date : 2022. 03. 23.
//  @ Author : 
//
//



import model.Virologist;
import model.codes.GeneticCode;

public class Laboratory extends Field
{
	private GeneticCode code;
	public void LearnGeneticCode(Virologist v)
	{
	}
}
