package model.map;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : map.Laboratory.java
//  @ Date : 2022. 03. 23.
//  @ Author : 
//
//



import model.Virologist;
import model.codes.GeneticCode;
import test.Tester;

/**
 *
 */
public class Laboratory extends Field
{
	private GeneticCode code;

	public Laboratory(GeneticCode c){
		Tester.methodStart(new Object(){}.getClass().getEnclosingMethod());

		code = c;

		Tester.methodEnd(new Object(){}.getClass().getEnclosingMethod());
	}

	public void LearnGeneticCode(Virologist v) {
		Tester.methodStart(new Object(){}.getClass().getEnclosingMethod());

		v.AddGeneticCode(code);

		Tester.methodEnd(new Object(){}.getClass().getEnclosingMethod());
	}
}
