package model.map;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : map.Shelter.java
//  @ Date : 2022. 03. 23.
//  @ Author : 
//
//


import model.Virologist;
import model.equipments.Equipment;
import test.Tester;

/**
 *
 */
public class Shelter extends Field
{
	public Shelter(Equipment e) {
		Tester.methodStart(new Object(){}.getClass().getEnclosingMethod());

		if (e != null)
			equipments.add(e);

		Tester.methodEnd(new Object(){}.getClass().getEnclosingMethod());
	}
}
