package model.map;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : map.Warehouse.java
//  @ Date : 2022. 03. 23.
//  @ Author : 
//
//


import model.Virologist;

public class Warehouse extends Field
{
	public void CollectMaterial(Virologist v)
	{
	}
}
