package model;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Game.java
//  @ Date : 2022. 03. 23.
//  @ Author : 
//
//



import model.codes.GeneticCode;
import model.map.Field;

public class Game
{
	private Field fields;
	private GeneticCode codes;
	public void NewGame()
	{
	}
	
	public void NextPlayer(int codes)
	{
	}
	
	public void EndGame()
	{
	}
	
	public void AddVirologist(Virologist v)
	{
	}
}
