package model;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Virologist.java
//  @ Date : 2022. 03. 23.
//  @ Author : 
//
//


import model.agents.*;
import model.codes.*;
import model.equipments.*;
import model.map.*;
import model.strategy.*;

public class Virologist
{
	private int actionCount;
	private int aminoAcid;
	private int nucleotide;
	private int maxAminoAcid;
	private int maxNucleotide;
	private Field field;
	private Agent agents;
	private GeneticCode codes;
	private Equipment equipments;
	private IMoveStr moveStr;
	private ILearnStr learnStr;
	private IInjectedStr injectedStr;
	private IDropStr dropStr;
	private ILootStr lootStr;
	private IEquipStr equipStr;
	private ICollectStr collectStr;
	private IInjectStr injectStr;
	private ILootedStr lootedStr;
	public void Move()
	{
	}
	
	public void Move(Field field)
	{
	}
	
	public void SetField(Field f)
	{
	}
	
	public void Drop()
	{
	}
	
	public void LootAminoAcidFrom(Virologist v)
	{
	}
	
	public void LootNucleotideFrom(Virologist v)
	{
	}
	
	public void LootEquipmentFrom(Virologist v)
	{
	}
	
	public void Collect()
	{
	}
	
	public void Learn()
	{
	}
	
	public void Equip()
	{
	}
	
	public void AddAgent(Agent a)
	{
	}
	
	public void RemoveAgent(Agent a)
	{
	}
	
	public void AddEquipment(Equipment e)
	{
	}
	
	public Equipment GetEquipment()
	{
	}
	
	public void AddGeneticCode(GeneticCode code)
	{
	}
	
	public void Inject(Virologist v, GeneticCode code)
	{
	}
	
	public boolean TargetedWith(Agent a)
	{
	}
	
	public void StealAminoAcid(Virologist self)
	{
	}
	
	public void StealNukleotid(Virologist self)
	{
	}
	
	public void StealEquipment(Virologist self)
	{
	}
	
	public void RemoveGeneticCodes()
	{
	}
	
	public void RemoveAgents()
	{
	}
	
	public void DecreaseActions()
	{
	}
	
	public void EndTurn()
	{
	}
	
	public void AddAminoAcid(int delta)
	{
	}
	
	public void AddNucleotide(int delta)
	{
	}
	
	public void RemoveNucleotide(int delta) throws Exception
	{
	}
	
	public void RemoveAminoAcid(int delta) throws Exception
	{
	}
	
	public void IncreaseLimit(int delta)
	{
	}
	
	public void DecreaseLimit(int delta)
	{
	}
	
	public int GetAminoAcid()
	{
	}
	
	public int GetNucleotide()
	{
	}
	
	public void Update()
	{
	}

	//azert lehetne private, mert a block-nak nem kell meghivnia, eleg a removeagents-et,
	// ami meg majd meghivja a restetet, de meg azert ne hivja meg a restet,
	// mert a szekvencian sem abrazoltam, hogy meghivna a restet
	public void Reset()
	{
	}
	
	public void SetDropStr(IDropStr d)
	{
	}
	
	public void SetMoveStr(IMoveStr m)
	{
	}
	
	public void SetLearnStr(ILearnStr l)
	{
	}
	
	public void SetLootStr(ILootStr l)
	{
	}
	
	public void SetInjectStr(IInjectStr i)
	{
	}
	
	public void SetInjectedStr(IInjectedStr l)
	{
	}
	
	public void SetEquipStr(IEquipStr e)
	{
	}
	
	public void SetCollectStr(ICollectStr c)
	{
	}
	
	public void SetLootedStr(ILootedStr l)
	{
	}
}
