//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Window.java
//  @ Date : 2022. 05. 07.
//  @ Author : 
//
//




public class Window extends Subject, Observer, Observer, Observer {
	private JMenuBar menuBar;
	private JButton endButton;
	private JProgressBar aminoBar;
	private JProgressBar nucleoBar;
	private JLabel aminoLabel;
	private JLabel nucleoLabel;
	private JLabel turnCounter;
	public JLabel actionBubbleMessage;
	public Observer Unnamed1;
	private Controller controller;
	public ActionBubble Unnamed3;
	public Background Unnamed4;
	public EquipmentBar Unnamed5;
	public TurnCounter Unnamed6;
	public MaterialBar Unnamed7;
	public Virologist Unnamed8;
	private Game game;
	public void Window(Controller controller, Game game) {
	}
	
	public void update() {
	}
	
	public void update() {
	}
	
	public void update() {
	}
	
	public void update() {
	}
}
