//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Background.java
//  @ Date : 2022. 05. 07.
//  @ Author : 
//
//




public class Background extends Observer {
	public Window Unnamed1;
	public void update() {
	}
}
