//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Drawable.java
//  @ Date : 2022. 05. 07.
//  @ Author : 
//
//




public class Drawable {
	public String getTexture() {
	}
}
