//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : InfectedLaboratory.java
//  @ Date : 2022. 05. 07.
//  @ Author : 
//
//




public class InfectedLaboratory {
}
