//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Virologist.java
//  @ Date : 2022. 05. 07.
//  @ Author : 
//
//




public class Virologist extends Subject {
}
